/**
 * Shared types used across main, preload, and renderer processes
 */

/**
 * Application settings structure
 */
export interface AppSettings {
  theme: 'light' | 'dark' | 'system';
  language: string;
  windowBounds?: {
    width: number;
    height: number;
    x?: number;
    y?: number;
  };
  lastOpened?: string;
  sidebarCollapsed?: boolean;
}

/**
 * Default settings values
 */
export const DEFAULT_SETTINGS: AppSettings = {
  theme: 'system',
  language: 'en',
  windowBounds: {
    width: 1200,
    height: 800,
  },
  sidebarCollapsed: false,
};

/**
 * IPC Response wrapper for consistent error handling
 */
export interface IPCResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

/**
 * Setting key type for type-safe settings access
 */
export type SettingKey = keyof AppSettings;

/**
 * App version info
 */
export interface AppVersion {
  app: string;
  electron: string;
  chrome: string;
  node: string;
}

/**
 * Navigation item definition
 */
export interface NavItem {
  id: string;
  label: string;
  icon: string;
  path: string;
}

/**
 * UI Layout preferences
 */
export interface LayoutPreferences {
  sidebarCollapsed: boolean;
}

/**
 * Git repository provider
 */
export type RepositoryProvider = 'github' | 'gitlab' | 'bitbucket' | 'other';

/**
 * Repository within a project
 */
export interface Repository {
  id: string;                           // UUID
  name?: string;                         // Display name (optional)
  url: string;                           // Git URL (required)
  defaultBranch?: string;                // e.g., 'main', 'master'
  provider?: RepositoryProvider;         // Git provider
}

/**
 * Project entity
 */
export interface Project {
  id: string;                           // UUID
  name: string;                         // Unique, case-insensitive
  tags: string[];                       // Array of tags
  repositories: Repository[];           // Associated repos
  createdAt: number;                    // Unix timestamp (ms)
  updatedAt: number;                    // Unix timestamp (ms)
}

/**
 * Form data for creating/updating projects
 */
export interface ProjectFormData {
  name: string;
  tags: string[];
  repositories: Omit<Repository, 'id'>[];  // IDs generated by service
}

/**
 * Validation error
 */
export interface ValidationError {
  field: string;
  message: string;
}
